//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace школа
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendancesForStudent
    {
        public int id { get; set; }
        public int attendance { get; set; }
        public int student { get; set; }
    
        public virtual attendance attendance1 { get; set; }
        public virtual student student1 { get; set; }
    }
}
