//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace школа
{
    using System;
    using System.Collections.Generic;
    
    public partial class homework
    {
        public int id { get; set; }
        public string text { get; set; }
        public string subject { get; set; }
        public System.DateTime date { get; set; }
        public int @class { get; set; }
    
        public virtual @class class1 { get; set; }
    }
}
